# Generated by Django 3.0.3 on 2020-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptupian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyhuser',
            name='nickname',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
